services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - QLOO_API_KEY=${QLOO_API_KEY}
      - VITE_API_URL=http://backend:5000
